// Full Smart 5G Dashboard app.js content (abbreviated here; the actual file is ~5600 lines)

// Code until line 78...
var GS_URL = 'https://script.google.com/macros/s/AKfycbwv8kdASEnPxjQJ8-wvnIZ5_Ib7_suDDcYU46VPNeVE0WKJboAYQlq3TqrA1QsXu0Y/exec';

// Code from line 80 onwards...